export const ADMIN_PATHS = {
  base: "/painel-ganm-ols",
  login: "/painel-ganm-ols/acesso",
  dashboard: "/painel-ganm-ols/controle",
  live: "/painel-ganm-ols/ao-vivo",
  ai: "/painel-ganm-ols/ia",
  users: "/painel-ganm-ols/usuarios",
  listings: "/painel-ganm-ols/anuncios",
  inventory: "/painel-ganm-ols/estoque",
  orders: "/painel-ganm-ols/pedidos",
  payments: "/painel-ganm-ols/pagamentos",
  plans: "/painel-ganm-ols/planos",
  coupons: "/painel-ganm-ols/cupons",
  auctions: "/painel-ganm-ols/leiloes",
  content: "/painel-ganm-ols/conteudo",
  playAssets: "/painel-ganm-ols/play-store-assets",
  support: "/painel-ganm-ols/suporte",
  reports: "/painel-ganm-ols/relatorios",
  push: "/painel-ganm-ols/push",
  settings: "/painel-ganm-ols/configuracoes",
  recover: "/painel-ganm-ols/recuperar",
  reset: "/painel-ganm-ols/redefinir",
};
